#**chapter 1_1 Intro NumPy**

#**Introduction to NumPy**

Day 1 [22 July 2020]

'* *การเรียบเรียง เป็นการนำความรู้จากหลาย ๆ แหล่งข้อมูลที่มีอยู่แล้ว มาปรับใช้ ปรับการเขียน ให้เหมาะสมกับการให้ความรู้แก่นักศึกษาในการอบรมครั้งนี้ ขอขอบคุณ และขออนุญาต ทุกแหล่งความรู้ที่ได้นำมาใช้ ณ ที่นี้ด้วยค่ะ*

# **บทนำ**
ในหัวข้อนี้ นักศึกษาจะได้ทำความรู้จักกับ NumPy, Pandas ซึ่งเป็น Library ของการเขียนโปรแกรมด้วยภาษา Python เพื่อนำไปใช้ประโยชน์ในงานด้าน Machine Learning อีกทั้ง Library ดังกล่าวถูกใช้อย่างแพร่หลายในงานด้าน data science ด้วย



# การนำเข้า Dataset File


เช่น ในตัวอย่าง google drive เก็บไฟล์ wine_data.csv ไว้ใน folder ชื่อ dataset

จากนั้น เราจะทำการ drive mount

drive mount
เพื่อเชื่อมโยง google drive ของเรากับ coloab เพื่อให้โปรแกรมที่เราเขียน มองเห็นไฟล์ใน google drive ได้ จะได้อ้างอิงและนำข้อมูลมาใช้งาน

เราใช้ from google.colab import drive ตามตัวอย่างนี้





In [1]:
# from google.colab import drive
# drive.mount('/content/drive') #ระวังเครื่องหมาย ‘ กับ ' ต่างกันนะคะ

ตอน run ด้านบนนี้ จะมีข้อความ เช่น

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947xxxxxxxxfpeopleapi.readonly

Enter your authorization code:

ให้คลิกที่ link ดังกล่าว หน้าต่างของ google จะปรากฎขึ้นมาให้

เพื่อให้เราอนุญาตให้ Google Drive File Stream มีการเข้าถึงบัญชี Google ของเราได้

ให้ตอบตกลง

จากนั้นจะปรากฎหน้าที่แสดงข้อความว่า

"

ลงชื่อเข้าใช้งาน

โปรดคัดลอกโค้ดนี้ไว้ สลับไปที่แอปพลิเคชันของคุณแล้ววางโค้ดลงไป:

4/1wHM128b4roXxxxxxxxxxxxxxxxxxxxx

"

ให้เรา copy โค้ท ของเรา เช่น 4/1wHM128b4roXxxxxxxxxxxxxxxxxxxxx**

มาวางในช่อง

Enter your authorization code:

เมื่อ run เสร็จเรียบร้อยแล้วจะมีข้อความ

Mounted at /content/drive

จากนั้น ให้สังเกตที่ด้านซ้ายมือของหน้าต่าง colab มีสัญลักษณ์รูป Folder Files

ให้คลิกเลือกที่สัญลักษณ์ดังกล่าว จากนั้น colab จะแสดงรายการ drive และ files ต่างๆ

ให้เราเลือกเข้าไปที่ files ที่ต้องการ เมื่อเจอแล้ว ให้คลิกขวาที่ไฟล์นั้่น แล้วเลือก copy path เอาไปวางใน code ตัวอย่างด้านล่างต่อจากนี้

ถ้านักศึกษา มองภาพไม่ออก ขอให้ดูตัวอย่างได้จากคลิปในยูทูปนี้ นะคะ

https://www.youtube.com/watch?v=TDyfhlg23vs&feature=youtu.be

ขอขอบคุณคลิปนี้ด้วยค่ะ

** หากเกิดปัญหา มองไม่เห็น drive **

ให้สังเกต ด้านซ้ายมือของหน้าต่าง colab มีสัญลักษณ์รูป Folder

เมื่อคลิกเลือกเข้าไป จะมีสัญลักษณ์ในรูป Folder 3 แบบ แบบที่มีหัวลูกศรขึ้น (upload), แบบมีหัวลูกศรวน (refresh), และแบบมีสัญสามเหลี่ยมใน folder (munt drive)

หากสัญลักษณ์รูป Folder แบบมีสามเหลี่ยมใน folder (mount drive) ไม่มีขีดทับบนสัญลักษณ์ ให้กดที่รูปนั้น เพื่อให้เกิดการ mount drive ก็จะมองเห็น folder แสดง path content > drive > My Drive > และ folder หรือ file ใน Google Drive ของตัวเราเอง ได้


In [2]:
! pip install pandas
import pandas as pd
path = './data/wine_data.csv'
myfiledata = pd.read_csv(path) ## Dataset is now stored in a Pandas Dataframe
myfiledata

1  14.23  1.71  2.43  15.6  127   2.8  3.06   .28  2.29   5.64  1.04  \
0    1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28   4.38  1.05   
1    1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81   5.68  1.03   
2    1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18   7.80  0.86   
3    1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82   4.32  1.04   
4    1  14.20  1.76  2.45  15.2  112  3.27  3.39  0.34  1.97   6.75  1.05   
..  ..    ...   ...   ...   ...  ...   ...   ...   ...   ...    ...   ...   
172  3  13.71  5.65  2.45  20.5   95  1.68  0.61  0.52  1.06   7.70  0.64   
173  3  13.40  3.91  2.48  23.0  102  1.80  0.75  0.43  1.41   7.30  0.70   
174  3  13.27  4.28  2.26  20.0  120  1.59  0.69  0.43  1.35  10.20  0.59   
175  3  13.17  2.59  2.37  20.0  120  1.65  0.68  0.53  1.46   9.30  0.60   
176  3  14.13  4.10  2.74  24.5   96  2.05  0.76  0.56  1.35   9.20  0.61   

     3.92  1065  
0    3.40  1050  
1    3.17  1185  
2    3.45  1480  
3    2.93   735  
4    2.85  1450  
..    ...   ...  
172  1.74   740  
173  1.56   750  
174  1.56   835  
175  1.62   840  
176  1.60   560  

[177 rows x 14 columns]

In [3]:
features = ["Cultivator", "Alchol", "Malic_Acid", "Ash", "Alcalinity_of_Ash", "Magnesium", "Total_phenols", "Falvanoids", "Nonflavanoid_phenols", "Proanthocyanins", "Color_intensity", "Hue", "OD280", "Proline"]
winedata = pd.read_csv(path, names = features) #ถ้าอ่านจาก drive ให้ใช้ ตัวแปร path
#winedata = pd.read_csv('wine_data.csv', names = features) #้ถ้าอ่านจาก local ให้ระบุชื่อไฟล์ได้เลย
#winedata.tail(20)
winedata.head(10)

Cultivator  Alchol  Malic_Acid   Ash  Alcalinity_of_Ash  Magnesium  \
0           1   14.23        1.71  2.43               15.6        127   
1           1   13.20        1.78  2.14               11.2        100   
2           1   13.16        2.36  2.67               18.6        101   
3           1   14.37        1.95  2.50               16.8        113   
4           1   13.24        2.59  2.87               21.0        118   
5           1   14.20        1.76  2.45               15.2        112   
6           1   14.39        1.87  2.45               14.6         96   
7           1   14.06        2.15  2.61               17.6        121   
8           1   14.83        1.64  2.17               14.0         97   
9           1   13.86        1.35  2.27               16.0         98   

   Total_phenols  Falvanoids  Nonflavanoid_phenols  Proanthocyanins  \
0           2.80        3.06                  0.28             2.29   
1           2.65        2.76                  0.26             1.28   
2           2.80        3.24                  0.30             2.81   
3           3.85        3.49                  0.24             2.18   
4           2.80        2.69                  0.39             1.82   
5           3.27        3.39                  0.34             1.97   
6           2.50        2.52                  0.30             1.98   
7           2.60        2.51                  0.31             1.25   
8           2.80        2.98                  0.29             1.98   
9           2.98        3.15                  0.22             1.85   

   Color_intensity   Hue  OD280  Proline  
0             5.64  1.04   3.92     1065  
1             4.38  1.05   3.40     1050  
2             5.68  1.03   3.17     1185  
3             7.80  0.86   3.45     1480  
4             4.32  1.04   2.93      735  
5             6.75  1.05   2.85     1450  
6             5.25  1.02   3.58     1290  
7             5.05  1.06   3.58     1295  
8             5.20  1.08   2.85     1045  
9             7.22  1.01   3.55     1045

In [4]:
winedata.head(20)

Cultivator  Alchol  Malic_Acid   Ash  Alcalinity_of_Ash  Magnesium  \
0            1   14.23        1.71  2.43               15.6        127   
1            1   13.20        1.78  2.14               11.2        100   
2            1   13.16        2.36  2.67               18.6        101   
3            1   14.37        1.95  2.50               16.8        113   
4            1   13.24        2.59  2.87               21.0        118   
5            1   14.20        1.76  2.45               15.2        112   
6            1   14.39        1.87  2.45               14.6         96   
7            1   14.06        2.15  2.61               17.6        121   
8            1   14.83        1.64  2.17               14.0         97   
9            1   13.86        1.35  2.27               16.0         98   
10           1   14.10        2.16  2.30               18.0        105   
11           1   14.12        1.48  2.32               16.8         95   
12           1   13.75        1.73  2.41               16.0         89   
13           1   14.75        1.73  2.39               11.4         91   
14           1   14.38        1.87  2.38               12.0        102   
15           1   13.63        1.81  2.70               17.2        112   
16           1   14.30        1.92  2.72               20.0        120   
17           1   13.83        1.57  2.62               20.0        115   
18           1   14.19        1.59  2.48               16.5        108   
19           1   13.64        3.10  2.56               15.2        116   

    Total_phenols  Falvanoids  Nonflavanoid_phenols  Proanthocyanins  \
0            2.80        3.06                  0.28             2.29   
1            2.65        2.76                  0.26             1.28   
2            2.80        3.24                  0.30             2.81   
3            3.85        3.49                  0.24             2.18   
4            2.80        2.69                  0.39             1.82   
5            3.27        3.39                  0.34             1.97   
6            2.50        2.52                  0.30             1.98   
7            2.60        2.51                  0.31             1.25   
8            2.80        2.98                  0.29             1.98   
9            2.98        3.15                  0.22             1.85   
10           2.95        3.32                  0.22             2.38   
11           2.20        2.43                  0.26             1.57   
12           2.60        2.76                  0.29             1.81   
13           3.10        3.69                  0.43             2.81   
14           3.30        3.64                  0.29             2.96   
15           2.85        2.91                  0.30             1.46   
16           2.80        3.14                  0.33             1.97   
17           2.95        3.40                  0.40             1.72   
18           3.30        3.93                  0.32             1.86   
19           2.70        3.03                  0.17             1.66   

    Color_intensity   Hue  OD280  Proline  
0              5.64  1.04   3.92     1065  
1              4.38  1.05   3.40     1050  
2              5.68  1.03   3.17     1185  
3              7.80  0.86   3.45     1480  
4              4.32  1.04   2.93      735  
5              6.75  1.05   2.85     1450  
6              5.25  1.02   3.58     1290  
7              5.05  1.06   3.58     1295  
8              5.20  1.08   2.85     1045  
9              7.22  1.01   3.55     1045  
10             5.75  1.25   3.17     1510  
11             5.00  1.17   2.82     1280  
12             5.60  1.15   2.90     1320  
13             5.40  1.25   2.73     1150  
14             7.50  1.20   3.00     1547  
15             7.30  1.28   2.88     1310  
16             6.20  1.07   2.65     1280  
17             6.60  1.13   2.57     1130  
18             8.70  1.23   2.82     1680  
19             5.10  0.96   3.36      845

# **numpy**
numpy เป็น library ที่ช่วยให้เราจัดการกับอาเรย์หลายมิติได้โดยง่ายขึ้น

ภาษา Python ไม่มีข้อมูลชนิด array แต่สามารถใช้ list แทนได้ แต่หากใช้ numpy ก็จะทำให้ใช้ข้อมูลชนิด array ได้ และทำงานกับข้อมูลอาเรย์หลายมิติก็ได้โดยง่ายไปอีก

ข้อแตกต่างระหว่าง array กับ list คือ array จะต้องประกอบด้วยข้อมูลเพียงชนิดเดียวเท่านั้น เรามักเห็นเป็นตัวเลขหมด เพราะมักใช้ในการคำนวณใน Machine Learning

numpy จะสร้าง array สำหรับเก็บข้อมูล โดยใช้ pointer ตัวเดียวชี้ไปที่ array นั้น ซึ่งทำให้ numpy มีประสิทธิภาพสูงสำหรับการทำการจัดการข้อมูลลักษณะนี้

numpy ถูกติดตั้งมาพร้อมกับการติดตั้ง Pyhton แล้ว เราจึงเรียกใช้งานได้เลย

ถ้ายังไม่มีการติดตั้งมา ให้ติดตั้งโดยใช้คำสั่ง เช่น
```
pip install numpy
```

การเรียใช้ numpy เข้ามาที่โปรแกรมหลักของเรา ทำได้โดย

In [5]:
! pip install numpy

import numpy as np

ต่อไปนี้ เราจะสามารถใช้ np แทน numpy ได้ตลอดทั้งโปรแกรม

### Creating an array

**Creating a single-dimensional array**

In [6]:
a = np.array([1,2,3]) # Calling the array function
print(a)

[1 2 3]


**Creating a multi-dimensional array**

Each set of elements within a square bracket indicates a row

Array of two rows and two columns

In [7]:
b = np.array([[1,2], [3,4]])
print(b)

[[1 2]
 [3 4]]


**Creating an ndarray by wrapping a list**

In [8]:
list1 = [1,2,3,4,5] # Creating a list
myarray = np.array(list1) # Wrapping the list
print(list1)
print(myarray)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


**Creating an array of numbers of a specified range**

In [9]:
myarray1 = np.arange(10, 100) # Array of numbers from 10 up to and excluding 100
print(myarray1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [10]:
myarray2 = np.arange(10, 100, 20) # Array of numbers from 10 up to and excluding 100 and step 20
print(myarray2)

[10 30 50 70 90]


**Creating a 5x5 array of zeroes**

In [11]:
arr2 = np.zeros((5,5))
print(arr2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


**Creating a linearly spaced vector, with spacing**

In [12]:
vector = np.linspace(0, 20, 5) # Start, stop, numbers
print(vector)

[ 0.  5. 10. 15. 20.]


**แบบฝึกหัด WS#2.1**
ให้นักเรียนทดลองสร้างชุดข้อมูลด้วย numpy โดยให้มีผลลัพธ์ดังนี้

[ 20 30 40 50 60 70 80 90 100]



In [13]:
vector1 = np.linspace(20, 100, 9, endpoint=True)
print(vector1)

[ 20.  30.  40.  50.  60.  70.  80.  90. 100.]


###**Indexing of numpy arrays**

NumPy array indexing is identical to Python's indexing scheme

In [14]:
myarray = np.arange(2, 20)
print(myarray)
element = myarray[6]
print(element)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
8


Python's concept of lists slicing is extended to NumPy.The slice object is constructed by providing start, stop, and step parameters to slice()

In [15]:
myarray = np.arange(20)
myarray_slice = slice(1, 10, 2) # Start, stop & step สไลส์ไปทีละ 2 ตัว เริ่มจาก 1 ถึง 10
myelement = myarray[6]
print(myarray)
print(myarray[myarray_slice])
print(myelement)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[1 3 5 7 9]
6


Slicing items beginning with a specified index

In [16]:
print(myarray[2:])

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


Slicing items until a specified index

In [17]:
print(myarray[:15])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


Extracting specific rows and columns using Slicing

In [18]:
d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(d)
print(d[0:2, 0:2]) # Slice the first two rows and the first two columns


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]


In [19]:
print(d[0:3, 0]) #from row 0 to n-1 rows, 1 column


[1 4 7]


In [20]:
print(d[0:2, 1:3])

[[2 3]
 [5 6]]


In [21]:
print(d[0:2, 0:3])

[[1 2 3]
 [4 5 6]]


In [22]:
print(d[1:2, 2:3])

[[6]]


In [23]:
#5 6
#8 9
#เขียนโปรแกรมตรงนี้ค่า
print(d[1:3, 1:3])

[[5 6]
 [8 9]]


In [24]:
print(d[0:2, 1:2])

[[2]
 [5]]


###**numpy array attributes**

In [25]:
print(d.shape) # Returns a tuple consisting of array dimensions
print(d.ndim) # Attribute returns the number of array dimensions
print(d.itemsize) # Returns the length of each element of array in bytes

(3, 3)
2
8


## Basic Statistics
ในหัวข้อ numpy นี้ ต้องการให้นักศึกษาทำความคุ้นเคยกับ numpy

เพื่อประโยชน์ในการทำมาวิเคราะห์ข้อมูล

numpy มีคำสั่งทางด้านสถิติหลายคำสั่ง ให้คำนวณได้อย่างง่าย เช่น

np.mean() ได้ค่าเฉลี่ยเลขคณิต

np.median() ได้ค่ามัธยฐาน

np.corrcoef() ใช้เมื่อต้องการดูว่ามีความสัมพันธ์ระหว่างสองตัวแปรในชุดข้อมูลของเราหรือกับคำอื่น ๆ ระหว่างสองอาร์เรย์ที่มีความยาวเท่ากัน

np.std() ได้ค่าเบี่ยงเบนมาตรฐาน

ตัวอย่าง

In [26]:
learning_hours = [1, 2, 6, 4, 10]
grades = [3, 4, 6, 5, 6]

a = np.mean(learning_hours)   # 4.6
b = np.median(learning_hours) # 4.0
c = np.std(learning_hours)    # 3.2
d = np.corrcoef(learning_hours, grades)

print(a)
print(b)
print(c)
print(d)

4.6
4.0
3.2
[[1.         0.88964891]
 [0.88964891 1.        ]]


# **แบบฝึกหัด WS#2.2**
ใ้ห้นักเรียนทดลองแสดงค่าเฉลี่ยและค่าส่วนเบี่ยงเบนมาตรฐานของข้อมูลคะแนนนักเรียนจำนวน 20 คน ซึ่งกำหนดข้อมูลคะแนนดังนี้

18, 20, 15, 6, 9, 10, 20, 19, 17, 13, 16, 7, 14, 15, 20, 4, 12, 17, 19, 18

In [27]:
data = np.array([18, 20, 15, 6, 9, 10, 20, 19, 17, 13, 16, 7, 14, 15, 20, 4, 12, 17, 19, 18])
print(data.mean())
print(data.std())

14.45
4.842261868176895


# **ทดลองกับชุดข้อมูล 2015StreetTreesCensus_TREES.csv**

 Using "2015StreetTreesCensus_TREES.csv" in google colab
[Download from New York City's tree census]( https://data.cityofnewyork.us/Environment/2015-Street-Tree-Census-Tree-Data/pi5s-9p35 )

In [28]:
# from google.colab import drive
import pandas as pd

# Path to the CSV file in your Google Drive
file_path = './data/2015StreetTreesCensus_TREES.csv'

# Read the CSV file into a pandas DataFrame
df = pd.read_csv(file_path)

# Display the first few rows of the dataframe
df.head(10)


created_at  tree_id  block_id  \
0  08/27/2015   180683    348711   
1  09/03/2015   200540    315986   
2  09/05/2015   204026    218365   
3  09/05/2015   204337    217969   
4  08/30/2015   189565    223043   
5  08/30/2015   190422    106099   
6  08/30/2015   190426    106099   
7  09/07/2015   208649    103940   
8  09/08/2015   209610    407443   
9  08/31/2015   192755    207508   

                                        the_geom  tree_dbh  stump_diam  \
0  POINT (-73.84421521958048 40.723091773924274)         3           0   
1   POINT (-73.81867945834878 40.79411066708779)        21           0   
2  POINT (-73.93660770459083 40.717580740099116)         3           0   
3  POINT (-73.93445615919741 40.713537494833226)        10           0   
4   POINT (-73.97597938483258 40.66677775537875)        21           0   
5  POINT (-73.98494997200308 40.770045625891846)        11           0   
6   POINT (-73.98533807200513 40.77020969000546)        11           0   
7    POINT (-73.98729652382876 40.7627238542921)         9           0   
8  POINT (-74.07625483097186 40.596579313729144)         6           0   
9   POINT (-73.96974394191379 40.58635724735751)        21           0   

         curb_loc status health                           spc_latin  ...  \
0          OnCurb  Alive   Fair                         Acer rubrum  ...   
1          OnCurb  Alive   Fair                   Quercus palustris  ...   
2          OnCurb  Alive   Good  Gleditsia triacanthos var. inermis  ...   
3          OnCurb  Alive   Good  Gleditsia triacanthos var. inermis  ...   
4          OnCurb  Alive   Good                     Tilia americana  ...   
5          OnCurb  Alive   Good  Gleditsia triacanthos var. inermis  ...   
6          OnCurb  Alive   Good  Gleditsia triacanthos var. inermis  ...   
7          OnCurb  Alive   Good                     Tilia americana  ...   
8          OnCurb  Alive   Good  Gleditsia triacanthos var. inermis  ...   
9  OffsetFromCurb  Alive   Fair               Platanus x acerifolia  ...   

  st_assem st_senate   nta                         nta_name  boro_ct  \
0       28        16  QN17                     Forest Hills  4073900   
1       27        11  QN49                       Whitestone  4097300   
2       50        18  BK90                East Williamsburg  3044900   
3       53        18  BK90                East Williamsburg  3044900   
4       44        21  BK37               Park Slope-Gowanus  3016500   
5       67        27  MN14                   Lincoln Square  1014500   
6       67        27  MN14                   Lincoln Square  1014500   
7       75        27  MN15                          Clinton  1012700   
8       64        23  SI14  Grasmere-Arrochar-Ft. Wadsworth  5006400   
9       45        23  BK26                        Gravesend  3037402   

      state   Latitude  longitude          x_sp           y_sp  
0  New York  40.723092 -73.844215  1.027431e+06  202756.768749  
1  New York  40.794111 -73.818679  1.034456e+06  228644.837379  
2  New York  40.717581 -73.936608  1.001823e+06  200716.891267  
3  New York  40.713537 -73.934456  1.002420e+06  199244.253136  
4  New York  40.666778 -73.975979  9.909138e+05  182202.425999  
5  New York  40.770046 -73.984950  9.884187e+05  219825.522669  
6  New York  40.770210 -73.985338  9.883112e+05  219885.278455  
7  New York  40.762724 -73.987297  9.877691e+05  217157.856088  
8  New York  40.596579 -74.076255  9.630732e+05  156635.554233  
9  New York  40.586357 -73.969744  9.926537e+05  152903.630594  

[10 rows x 42 columns]

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 683788 entries, 0 to 683787
Data columns (total 42 columns):
 #   Column      Non-Null Count   Dtype  
---  ------      --------------   -----  
 0   created_at  683788 non-null  object 
 1   tree_id     683788 non-null  int64  
 2   block_id    683788 non-null  int64  
 3   the_geom    683788 non-null  object 
 4   tree_dbh    683788 non-null  int64  
 5   stump_diam  683788 non-null  int64  
 6   curb_loc    683788 non-null  object 
 7   status      683788 non-null  object 
 8   health      652172 non-null  object 
 9   spc_latin   652169 non-null  object 
 10  spc_common  652169 non-null  object 
 11  steward     164350 non-null  object 
 12  guards      79866 non-null   object 
 13  sidewalk    652172 non-null  object 
 14  user_type   683788 non-null  object 
 15  problems    225844 non-null  object 
 16  root_stone  683788 non-null  object 
 17  root_grate  683788 non-null  object 
 18  root_other  683788 non-null  object 
 19  tr

In [30]:
# prompt: how to show all columns in dataframe
import pandas as pd
pd.set_option('display.max_columns', None)


In [31]:
df.head(10)

created_at  tree_id  block_id  \
0  08/27/2015   180683    348711   
1  09/03/2015   200540    315986   
2  09/05/2015   204026    218365   
3  09/05/2015   204337    217969   
4  08/30/2015   189565    223043   
5  08/30/2015   190422    106099   
6  08/30/2015   190426    106099   
7  09/07/2015   208649    103940   
8  09/08/2015   209610    407443   
9  08/31/2015   192755    207508   

                                        the_geom  tree_dbh  stump_diam  \
0  POINT (-73.84421521958048 40.723091773924274)         3           0   
1   POINT (-73.81867945834878 40.79411066708779)        21           0   
2  POINT (-73.93660770459083 40.717580740099116)         3           0   
3  POINT (-73.93445615919741 40.713537494833226)        10           0   
4   POINT (-73.97597938483258 40.66677775537875)        21           0   
5  POINT (-73.98494997200308 40.770045625891846)        11           0   
6   POINT (-73.98533807200513 40.77020969000546)        11           0   
7    POINT (-73.98729652382876 40.7627238542921)         9           0   
8  POINT (-74.07625483097186 40.596579313729144)         6           0   
9   POINT (-73.96974394191379 40.58635724735751)        21           0   

         curb_loc status health                           spc_latin  \
0          OnCurb  Alive   Fair                         Acer rubrum   
1          OnCurb  Alive   Fair                   Quercus palustris   
2          OnCurb  Alive   Good  Gleditsia triacanthos var. inermis   
3          OnCurb  Alive   Good  Gleditsia triacanthos var. inermis   
4          OnCurb  Alive   Good                     Tilia americana   
5          OnCurb  Alive   Good  Gleditsia triacanthos var. inermis   
6          OnCurb  Alive   Good  Gleditsia triacanthos var. inermis   
7          OnCurb  Alive   Good                     Tilia americana   
8          OnCurb  Alive   Good  Gleditsia triacanthos var. inermis   
9  OffsetFromCurb  Alive   Fair               Platanus x acerifolia   

         spc_common steward   guards  sidewalk         user_type     problems  \
0         red maple     NaN      NaN  NoDamage  TreesCount Staff          NaN   
1           pin oak     NaN      NaN    Damage  TreesCount Staff       Stones   
2       honeylocust    1or2      NaN    Damage         Volunteer          NaN   
3       honeylocust     NaN      NaN    Damage         Volunteer       Stones   
4   American linden     NaN      NaN    Damage         Volunteer       Stones   
5       honeylocust    1or2  Helpful  NoDamage         Volunteer          NaN   
6       honeylocust    1or2  Helpful  NoDamage         Volunteer          NaN   
7   American linden     NaN      NaN  NoDamage         Volunteer  MetalGrates   
8       honeylocust     NaN      NaN  NoDamage  TreesCount Staff          NaN   
9  London planetree     NaN      NaN  NoDamage  TreesCount Staff          NaN   

  root_stone root_grate root_other trnk_wire trnk_light trnk_other brnch_ligh  \
0         No         No         No        No         No         No         No   
1        Yes         No         No        No         No         No         No   
2         No         No         No        No         No         No         No   
3        Yes         No         No        No         No         No         No   
4        Yes         No         No        No         No         No         No   
5         No         No         No        No         No         No         No   
6         No         No         No        No         No         No         No   
7         No        Yes         No        No         No         No         No   
8         No         No         No        No         No         No         No   
9         No         No         No        No         No         No         No   

  brnch_shoe brnch_othe             address  zipcode       zip_city  cb_num  \
0         No         No   108-005 70 AVENUE    11375   Forest Hills     406   
1         No         No    147-074 7 AVENUE    11357     Whitestone

** Get column titles**

In [32]:
# Convert the DataFrame to a Numpy array
tree_census = df.to_numpy()

# Get column titles
column_titles = df.columns.to_numpy()
print("Column Titles:", column_titles)

print("Column Titles:", column_titles[27])
print("Column Titles:", column_titles[2])
print("Column Titles:", column_titles[4])

Column Titles: ['created_at' 'tree_id' 'block_id' 'the_geom' 'tree_dbh' 'stump_diam'
 'curb_loc' 'status' 'health' 'spc_latin' 'spc_common' 'steward' 'guards'
 'sidewalk' 'user_type' 'problems' 'root_stone' 'root_grate' 'root_other'
 'trnk_wire' 'trnk_light' 'trnk_other' 'brnch_ligh' 'brnch_shoe'
 'brnch_othe' 'address' 'zipcode' 'zip_city' 'cb_num' 'borocode'
 'boroname' 'cncldist' 'st_assem' 'st_senate' 'nta' 'nta_name' 'boro_ct'
 'state' 'Latitude' 'longitude' 'x_sp' 'y_sp']
Column Titles: zip_city
Column Titles: block_id
Column Titles: tree_dbh


**Slicing and indexing trees**

In [33]:
# Select all rows of block ID data from the second column
block_ids = tree_census[:, 2]

# Print the first five block_ids
print(block_ids[:5])

# Select the tenth block ID from block_ids
tenth_block_id = block_ids[9]
print(tenth_block_id)

# Select five block IDs from block_ids starting with the tenth ID
block_id_slice = block_ids[9:14]
print(block_id_slice)

[348711 315986 218365 217969 223043]
207508
[207508 302371 302371 415896 219493]


**Slicing and Indexing trees: specify the step size**

In [34]:
# Create an array of the first 100 trunk diameters from tree_census
hundred_diameters = tree_census[:100, 4]
print(hundred_diameters,"\n")

# Create an array of trunk diameters with even row indices from 50 to 100 inclusive
every_diameter = tree_census[50:101, 4]
print(every_diameter,"\n")

# Specify the step size
every_two_diameter = tree_census[50:101:2, 4]
print(every_two_diameter)

[3 21 3 10 21 11 11 9 6 21 11 8 13 22 30 12 2 14 14 10 11 14 4 9 2 5 33 19
 9 9 7 3 7 5 4 12 13 12 24 20 13 12 36 29 6 9 18 13 13 9 19 17 32 28 7 10
 5 3 8 10 6 2 8 5 5 26 10 18 11 25 15 13 5 26 36 16 13 2 2 4 22 28 42 12 3
 3 26 3 26 18 24 32 13 11 22 38 18 2 29 11] 

[19 17 32 28 7 10 5 3 8 10 6 2 8 5 5 26 10 18 11 25 15 13 5 26 36 16 13 2
 2 4 22 28 42 12 3 3 26 3 26 18 24 32 13 11 22 38 18 2 29 11 23] 

[19 32 7 5 8 6 8 5 10 11 15 5 36 13 2 22 42 3 26 26 24 13 22 18 29 23]


**Sorting trees**

In [35]:
sorted_diameters = np.sort(tree_census[:, 4])
print(sorted_diameters,"\n")
print(sorted_diameters[-100:])

[0 0 0 ... 389 425 450] 

[74 74 74 74 75 76 76 77 78 79 79 80 80 80 81 87 88 88 88 89 89 89 89 91
 94 94 98 99 99 100 102 104 105 106 106 109 109 110 110 118 120 120 122
 123 123 127 127 128 131 132 132 139 140 141 141 142 143 145 147 149 149
 151 154 159 164 165 168 169 170 172 172 175 177 181 183 195 198 199 204
 204 204 210 217 228 234 248 250 255 261 266 281 282 291 293 298 318 318
 389 425 450]


**Using np.where()**

In [36]:
# Create an array of row_indices for trees on block 219890
row_indices = np.where(tree_census[:, 2] == 219890)
print(row_indices)

# Specify columns to include in the subset create_at, block_id, tree_dbh, zip_city
columns_to_include = [0, 2, 4, 27]

# Create an array which only contains data for trees on block 219890
block_219890 = tree_census[row_indices][:, columns_to_include]
print("Block 219890 Data:\n", block_219890)

(array([551980, 553978, 554466, 555946, 562030, 575243, 679352]),)
Block 219890 Data:
 [['07/12/2015' 219890 110 'Brooklyn']
 ['07/12/2015' 219890 88 'Brooklyn']
 ['07/12/2015' 219890 79 'Brooklyn']
 ['07/12/2015' 219890 104 'Brooklyn']
 ['07/12/2015' 219890 0 'Brooklyn']
 ['07/12/2015' 219890 3 'Brooklyn']
 ['07/12/2015' 219890 2 'Brooklyn']]


**Creating arrays from conditions**

In [37]:
# Find indices where tree_dbh == 88
indices = np.where(tree_census[:, 4] == 88)[0]
print(indices)

trunk_stump_diameters = tree_census[indices,27] # 27 is column id
print(trunk_stump_diameters,"\n")

# Find indices where tree_dbh > 200
indices = np.where(tree_census[:, 4] > 200)[0]
trunk_stump_diameters = tree_census[indices, 27]
print(trunk_stump_diameters,"\n")

print(trunk_stump_diameters[:5])
print(trunk_stump_diameters[-5:])

[100167 487485 553978]
['New York' 'Jamaica' 'Brooklyn'] 

['Brooklyn' 'Bayside' 'Staten Island' 'Staten Island' 'New York'
 'Brooklyn' 'Jamaica' 'Springfield Gardens' 'Bronx' 'Brooklyn' 'Bronx'
 'Brooklyn' 'Staten Island' 'Bronx' 'New York' 'Staten Island'
 'Far Rockaway' 'Brooklyn' 'Brooklyn' 'Brooklyn' 'Howard Beach'
 'Forest Hills'] 

['Brooklyn' 'Bayside' 'Staten Island' 'Staten Island' 'New York']
['Brooklyn' 'Brooklyn' 'Brooklyn' 'Howard Beach' 'Forest Hills']


##  แบบฝึกหัด Statistics with TreeData

ให้นักศึกษาแสดงค่ารวมของจำนวนต้นไม้ และ ค่าเฉลี่ยของจำนวนต้นไม้ทั้งหมดที่มี
(column cb_num)  

**ตัวอย่าง Output**

Sum the number of tree: 234884873

Mean the number of tree: 343.50540372162135

In [42]:
tree_census = df.to_numpy()
column_titles = df.columns.to_numpy()

# Find column index for cb_num
cb_num_index = np.where(column_titles == 'cb_num')[0][0]

sum_cb_num = np.sum(tree_census[:, cb_num_index])
print(f"Sum the number of tree: {sum_cb_num:,}")

mean_cb_num = np.mean(tree_census[:, cb_num_index])
print(f"Mean the number of tree: {mean_cb_num:,.2f}")

Sum the number of tree: 234,884,873
Mean the number of tree: 343.51


ให้นักศึกษาแสดงจำนวนต้นไม้ทั้งหมดที่มีเฉพาะเมือง Newyork

**ตัวอย่าง Output**

Sum  of Trees at New York City: 6,909,057.00


In [44]:
zip_city_index = np.where(column_titles == 'zip_city')[0][0]

# Find indices where zip_city == New York
indices = np.where(tree_census[:, zip_city_index] == 'New York')[0]

# Find the sum of cb_num for trees in New York
sum_cb_num = np.sum(tree_census[indices, cb_num_index])

print(f"Sum of Trees at New York City: {sum_cb_num:,.2f}")

Sum of Trees at New York City: 6,909,057.00
